name: Terraform Apply
run-name: Terraform Plan for ${{ github.event.pull_request.head.ref }}

on:  
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    name: Terraform Apply

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IMMUNE_ROLE_ARN }}
          role-session-name: TerraformSession
          aws-region: ${{ secrets.REGION }}
          
      - name: Check Role
        run: |
          aws sts get-caller-identity 

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve